#!/bin/bash
# This file is automatically generated by se306_p1_package/world/updateactors.py
export ROS_PACKAGE_PATH=`pwd`:$ROS_PACKAGE_PATH

roscore & ROSCORE_PID=$!

rosrun se306_p1_package ActorSpawner 0 R0 &
rosrun se306_p1_package ActorSpawner 1 R1 &
rosrun se306_p1_package ActorSpawner 2 Resident &

rosrun stage_ros stageros se306_p1_package/world/myworld.world

kill $ROSCORE_PID