/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/jenna/se306_ws/src/se306_p1_pkg/msg/Interaction.msg
 *
 */


#ifndef SE306_P1_PKG_MESSAGE_INTERACTION_H
#define SE306_P1_PKG_MESSAGE_INTERACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace se306_p1_pkg
{
template <class ContainerAllocator>
struct Interaction_
{
  typedef Interaction_<ContainerAllocator> Type;

  Interaction_()
    : attribute()  {
    }
  Interaction_(const ContainerAllocator& _alloc)
    : attribute(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _attribute_type;
  _attribute_type attribute;




  typedef boost::shared_ptr< ::se306_p1_pkg::Interaction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::se306_p1_pkg::Interaction_<ContainerAllocator> const> ConstPtr;

}; // struct Interaction_

typedef ::se306_p1_pkg::Interaction_<std::allocator<void> > Interaction;

typedef boost::shared_ptr< ::se306_p1_pkg::Interaction > InteractionPtr;
typedef boost::shared_ptr< ::se306_p1_pkg::Interaction const> InteractionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::se306_p1_pkg::Interaction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::se306_p1_pkg::Interaction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace se306_p1_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'se306_p1_pkg': ['/home/jenna/se306_ws/src/se306_p1_pkg/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::se306_p1_pkg::Interaction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::se306_p1_pkg::Interaction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se306_p1_pkg::Interaction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::se306_p1_pkg::Interaction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se306_p1_pkg::Interaction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::se306_p1_pkg::Interaction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::se306_p1_pkg::Interaction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b718a1f64372c4ec6cb016022002bad8";
  }

  static const char* value(const ::se306_p1_pkg::Interaction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb718a1f64372c4ecULL;
  static const uint64_t static_value2 = 0x6cb016022002bad8ULL;
};

template<class ContainerAllocator>
struct DataType< ::se306_p1_pkg::Interaction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "se306_p1_pkg/Interaction";
  }

  static const char* value(const ::se306_p1_pkg::Interaction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::se306_p1_pkg::Interaction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string attribute\n\
";
  }

  static const char* value(const ::se306_p1_pkg::Interaction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::se306_p1_pkg::Interaction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.attribute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Interaction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::se306_p1_pkg::Interaction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::se306_p1_pkg::Interaction_<ContainerAllocator>& v)
  {
    s << indent << "attribute: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.attribute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SE306_P1_PKG_MESSAGE_INTERACTION_H
